CREATE TABLE TBLUSERS (
  USER_ID varchar(255) NOT NULL,
  USERNAME varchar(255) DEFAULT NULL,
  PASSWORD varchar(255) DEFAULT NULL,
  IS_ENABLED varchar(255) DEFAULT NULL,
  CREATED_AT datetime DEFAULT NULL,
  UPDATED_AT datetime DEFAULT NULL,
  PRIMARY KEY (USER_ID)
)

CREATE TABLE spring_data_jdbc.TBLSEQENCE (
  SEQ_NAME varchar(50) NOT NULL,
  SEQ_PREFIX varchar(10) DEFAULT NULL,
  SEQ_NUMBER decimal(16, 0) DEFAULT NULL,
  PRIMARY KEY (SEQ_NAME)
)

CREATE DEFINER=`root`@`%` FUNCTION `GENERATE_SEQ_ID`(P_SEQ_PREFIX VARCHAR(50)) RETURNS varchar(25) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
  DECLARE V_NEWBPID varchar(25);
  DECLARE V_SEQ_NUMBER decimal(25,0);
  SELECT t.SEQ_NUMBER INTO V_SEQ_NUMBER FROM TBLSEQENCE t WHERE t.SEQ_PREFIX = P_SEQ_PREFIX; 
  UPDATE TBLSEQENCE t SET t.SEQ_NUMBER = V_SEQ_NUMBER+1 WHERE t.SEQ_PREFIX = P_SEQ_PREFIX;
RETURN CONCAT(P_SEQ_PREFIX, V_SEQ_NUMBER+1);
END


CREATE DEFINER=`root`@`%` PROCEDURE `usp_TBLUSERS_Update`(IN p_USER_ID VARCHAR(255), IN p_USERNAME VARCHAR(255), IN p_PASSWORD VARCHAR(255), IN p_IS_ENABLED varchar(255))
BEGIN
    START TRANSACTION;

    UPDATE TBLUSERS
    SET    USERNAME = p_USERNAME, PASSWORD = p_PASSWORD, IS_ENABLED = p_IS_ENABLED, 
           UPDATED_AT = SYSDATE()
    WHERE  USER_ID = p_USER_ID;

    COMMIT;
END

CREATE DEFINER=`root`@`%` PROCEDURE `usp_TBLUSERS_Select`()
BEGIN
    START TRANSACTION;

    SELECT USER_ID, USERNAME, PASSWORD, IS_ENABLED, CREATED_AT, UPDATED_AT
    FROM   TBLUSERS;

    COMMIT;
END

CREATE DEFINER=`root`@`%` PROCEDURE `usp_TBLUSERS_Insert`(IN p_USERNAME VARCHAR(255), IN p_PASSWORD VARCHAR(255), IN p_IS_ENABLED VARCHAR(255))
BEGIN

    START TRANSACTION;

    INSERT INTO TBLUSERS (USER_ID, USERNAME, PASSWORD, IS_ENABLED, CREATED_AT, UPDATED_AT)
    VALUES (GENERATE_SEQ_ID('US'), p_USERNAME, p_PASSWORD, p_IS_ENABLED, SYSDATE(), SYSDATE());

    COMMIT;
END

CREATE DEFINER=`root`@`%` PROCEDURE `usp_TBLUSERS_Delete`(p_USER_ID VARCHAR(255))
BEGIN
    START TRANSACTION;

    DELETE
    FROM   TBLUSERS
    WHERE  USER_ID = p_USER_ID;

    COMMIT;
END